openapi: 3.0.0
info:
  title: Social App
  description: Our first Social app at LCO - Debajit
  version: 0.1.0

servers:
  - url: http://localhost:4000/api/v1
    description: localhost version of our app
  - url: https://socialmedia-backend-30iu.onrender.com/api/v1
    description: this is the deployed version of the api

paths:
  /instagram:
    get:
      summary: returns username, followers and followings
      responses:
        '200': # status code
          description: returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: number
                  following:
                    type: number
  /facebook:
    get:
      summary: returns username, followers and followings
      responses:
        '200': # status code
          description: returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: number
                  following:
                    type: number
  /linkedin:
    get:
      summary: returns username, followers and followings
      responses:
        '200': # status code
          description: returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: number
                  following:
                    type: number
  /{id}:
    get:
      summary: returns whatever is there in parameters
      parameters:
        - name: id
          default: 5
          in: path
          schema:
            type: string
      responses:
        '200': # status code
          description: returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  params:
                    type: string
